name: 🐞 Bug Report
description: Report issues encountered in the application
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the bug in detail. Add screenshots if necessary.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What should have happened?
      placeholder: Write your explanation here...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps required to reproduce the bug
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment Information
      description: Information such as OS, browser, app version, etc.
      placeholder: macOS, Chrome 125, v1.3.2 etc.
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
