name: 🌟 Feature Request
description: Suggest a new feature
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Do you have an idea for a new feature? Awesome! Please fill out the form below.

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      placeholder: What are you proposing?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is it needed?
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there any alternative ways to provide this feature?
      placeholder: Alternative solutions...
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Notes
