name: 🧠 Logic Anomaly
description: Report cases where the code behaves incorrectly due to logic errors
title: "[ANOMALY] "
labels: [logic-anomaly]
body:
  - type: markdown
    attributes:
      value: |
        Did you notice the code behaving unexpectedly or incorrectly? Please provide details.

  - type: textarea
    id: anomaly_description
    attributes:
      label: Anomaly Description
      placeholder: What did you expect, what happened?
    validations:
      required: true

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Expected vs Actual Behavior
      placeholder: |
        Expected:
        Actual:
    validations:
      required: true

  - type: textarea
    id: code_example
    attributes:
      label: Relevant Code or Flow
      description: Add a code snippet, pseudocode, or relevant file structure
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What are the consequences of this logic error?
    validations:
      required: false
